//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LievenCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public int ArtikelId { get; set; }
        public string Naam { get; set; }
        public byte[] Inhoud { get; set; }
        public Nullable<decimal> Prijs { get; set; }
        public bool Publish { get; set; }
    
        public virtual Afbeelding Afbeelding { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Onderverdeling Onderverdeling { get; set; }
        public virtual User User { get; set; }
    }
}
