//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LievenCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string Naam { get; set; }
        public string Adres { get; set; }
        public string Telefoon { get; set; }
        public string ExtraTelefoon { get; set; }
        public string Email { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual User User { get; set; }
    }
}
