//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LievenCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Onderverdeling
    {
        public int OnderverdelingId { get; set; }
        public string Naam { get; set; }
    
        public virtual Afdeling Afdeling { get; set; }
        public virtual Artikel Artikel { get; set; }
    }
}
